### ISSUE TITLE
Cannot create a topic in the remote kafka server

### ISSUE THREAD

**Issue by iShiBin** [airztz/CS502Capstone#5]
Hi,

Here is the command I run and the error message I encounter. Could you please help?

>Bin:bin bin$ ./kafka-topics.sh --create --zookeeper node1:2181 --replication-factor 1 --partitions 1 --topic test
Error while executing topic command : Replication factor: 1 larger than available brokers: 0.
[2018-01-18 15:31:40,520] ERROR org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 1 larger than available brokers: 0.
 (kafka.admin.TopicCommand$)

I tried using all the 3 hosts but all failed. Can you please help to create this test topic so that I can move forward?

By the way, I've completed a sample producer in my local.

**Comment by airztz** [comment]
Use the following command:
./kafka-topics.sh --create --zookeeper ip:2181/kafka --replication-factor 1 --partitions 1 --topic test

I already created a topic for testing: input_cs502, you just can use this one.

**Comment by iShiBin** [comment]
* I don't see the difference between your command and mine. Why?
* I used input_cs502 as for now. I am using 'mv_0006972.txt' as the test file. Can you see the stream?

**Comment by iShiBin** [comment]
Let's keep this thread open until I can send msg to the topic successfully. 

Now, the problem is I cannot get the messages on my console. Can you please check from your end?
>./kafka-console-consumer.sh --zookeeper 34.215.130.174:2181 --topic input_cs502 --from-beginning
<no messages here>

**Comment by airztz** [comment]
Pls use --zookeeper ip:2181/kafka 

I made a subfolder named kafka to store our kafka cluster's meta data.

**Comment by iShiBin** [comment]
Now I see. Thanks. By the way, what is wrong with my consumer command. Can you correct it?

**Comment by airztz** [comment]
./kafka-console-consumer.sh --zookeeper node1:2181/kafka --topic input_cs502 --from-beginning

**Comment by airztz** [comment]
kafka-console-consumer.sh --bootstrap-server node1:9092,node2:9092,node3:9092 --topic input_cs502 --from-beginning --formatter kafka.tools.DefaultMessageFormatter --property print.key=true --property print.value=true

**Comment by iShiBin** [comment]
Got it. Thanks. I am going to close this issue.
