### ISSUE TITLE
Cannot send movie title data to kafka server!

### ISSUE THREAD

**Issue by iShiBin** [airztz/CS502Capstone#6]
The sending hangs on this record: (This 2048 is too weired 1024 * 2). I tried 3 times and it is the same problem.
>2048,1966,The Glass Bottom Boat

And then errors out as below. Will it be the kafka cofigure issue? 
>Traceback (most recent call last):
  File "/Users/bin/Documents/NEU/Courses/cs502/capstone/ingestion/movie.py", line 16, in <module>
    producer.send(topic = topic_name, value = msg, timestamp_ms=datetime.now())
  File "/Library/Python/2.7/site-packages/kafka/producer/kafka.py", line 528, in send
    self.config['max_block_ms'])
  File "/Library/Python/2.7/site-packages/kafka/producer/record_accumulator.py", line 247, in append
    buf = self._free.allocate(size, max_time_to_block_ms)
  File "/Library/Python/2.7/site-packages/kafka/producer/buffer.py", line 202, in allocate
    "Failed to allocate memory within the configured"
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to allocate memory within the configured max blocking time

**Comment by airztz** [comment]
The topic configuration is the same as 'input_cs502'. I haven't met this bug before.
Is this bug triggered only by the record below?
"2048,1966,The Glass Bottom Boat"

**Comment by iShiBin** [comment]
No. I tried only 20 records. My problem ends correctly. But the messages have not delivered.

**Comment by iShiBin** [comment]
It was a bug with the timestamp issue. Now, it is fixed.
